
BIN_LIB=CMPSYS
LIBLIST=$(BIN_LIB) FINCLIDAT FINPLTDAT FINCOODAT FINCOOOBJ 
SHELL=/QOpenSys/usr/bin/qsh

all: TCSAT0045.sqlrpgle

%.rpgle:
	system -s "CHGATR OBJ('./QRPGLESRC/$*.rpgle') ATR(*CCSID) VALUE(1252)"
	liblist -a $(LIBLIST);\
	system "CRTBNDRPG PGM($(BIN_LIB)/$*) SRCSTMF('./QRPGLESRC/$*.rpgle') OPTION(*EVENTF) DBGVIEW(*LIST) TGTRLS(*CURRENT)"

%.sqlrpgle:
	system -s "CHGATR OBJ('./QRPGLESRC/$*.sqlrpgle') ATR(*CCSID) VALUE(1252)"
	liblist -a $(LIBLIST);\
	system "CRTSQLRPGI OBJ($(BIN_LIB)/$*) SRCSTMF('./QRPGLESRC/$*.sqlrpgle') OBJTYPE(*PGM) REPLACE(*YES)"
